import type { ExplorerMode, Region, Species, SpeciesId } from "@/lib/types";

const sharedRegions: Region[] = [
  {
    id: "frontal",
    name: "Frontal command cortex",
    summary: "Planning, voluntary action, social prediction, and executive control.",
    energyUsage: 88,
    dominance: 92,
    evolution: "Expanded dramatically in social mammals and primates.",
    color: "#65e7dc",
    detail: {
      microstructures: ["Association cortex", "Motor planning bands", "Inhibitory control loops"],
      pathway: "Routes intent through motor planning, reward prediction, and social inference circuits.",
      studyPrompt: "Rotate the frontal shell and inspect how executive fibers fan into motor regions.",
    },
  },
  {
    id: "temporal",
    name: "Temporal memory arrays",
    summary: "Sound recognition, object identity, memory indexing, and language traces.",
    energyUsage: 74,
    dominance: 76,
    evolution: "Links sensory detail with learned context and recall.",
    color: "#a890ff",
    detail: {
      microstructures: ["Hippocampal index", "Auditory maps", "Object recognition columns"],
      pathway: "Binds sensory signatures into memory snapshots that can be recalled and compared.",
      studyPrompt: "Use detailed view to isolate memory bands and compare them with optic input.",
    },
  },
  {
    id: "optic",
    name: "Optic processing field",
    summary: "Visual mapping, motion detection, depth estimates, and scene parsing.",
    energyUsage: 82,
    dominance: 84,
    evolution: "Specializes differently in predators, birds, and primates.",
    color: "#f5b95d",
    detail: {
      microstructures: ["Retinotopic sheets", "Motion detectors", "Depth fusion relays"],
      pathway: "Transforms light patterns into motion, edge, and position maps for rapid decisions.",
      studyPrompt: "Turn on cross-section to reveal layered visual maps and dominance gradients.",
    },
  },
  {
    id: "cerebellum",
    name: "Cerebellar precision engine",
    summary: "Balance, timing, motor learning, predictive correction, and fine control.",
    energyUsage: 69,
    dominance: 80,
    evolution: "Highly conserved across vertebrates for movement calibration.",
    color: "#5ab7ff",
    detail: {
      microstructures: ["Purkinje-like bands", "Timing loops", "Balance correction nuclei"],
      pathway: "Compares intended movement with sensory feedback and sends correction pulses.",
      studyPrompt: "Explode the model to inspect the compact correction engine behind motion.",
    },
  },
  {
    id: "brainstem",
    name: "Brainstem survival core",
    summary: "Breathing, reflexes, arousal, heart rhythm, and autonomic survival loops.",
    energyUsage: 58,
    dominance: 72,
    evolution: "Ancient architecture shared by nearly all vertebrate brains.",
    color: "#79d38a",
    detail: {
      microstructures: ["Reflex nuclei", "Arousal columns", "Autonomic rhythm centers"],
      pathway: "Maintains survival rhythms while routing reflexive signals to the body.",
      studyPrompt: "Peel layers to see how newer regions remain anchored to the survival core.",
    },
  },
  {
    id: "olfactory",
    name: "Olfactory navigation mesh",
    summary: "Scent identity, chemical trails, food detection, and social signatures.",
    energyUsage: 48,
    dominance: 61,
    evolution: "Dominates species that map the world through chemical information.",
    color: "#ff8fb5",
    detail: {
      microstructures: ["Chemical identity bulbs", "Trail memory fibers", "Social scent relays"],
      pathway: "Converts chemical gradients into identity, direction, and survival context.",
      studyPrompt: "Focus this region to inspect scent-route relays and species-specific dominance.",
    },
  },
];

const regionTuning: Record<SpeciesId, Partial<Record<Region["id"], Partial<Region>>>> = {
  human: {
    frontal: { dominance: 98, energyUsage: 94 },
    temporal: { summary: "Language, narrative memory, social meaning, and auditory recognition." },
    olfactory: { dominance: 38 },
  },
  primate: {
    frontal: { dominance: 90 },
    optic: { summary: "Depth-rich visual inference for canopy navigation and hand targeting." },
  },
  bird: {
    optic: { dominance: 96, energyUsage: 90 },
    cerebellum: { dominance: 88, summary: "Flight stabilization, timing, vocal learning, and acrobatic correction." },
  },
  snake: {
    olfactory: { dominance: 93, summary: "Forked-tongue chemical mapping and prey trail reconstruction." },
    frontal: { dominance: 38 },
  },
  fish: {
    brainstem: { dominance: 91 },
    optic: { summary: "Fast schooling alignment, looming-threat detection, and water-column tracking." },
  },
  cat: {
    optic: { dominance: 91, summary: "Low-light motion tracking, depth targeting, and ambush prediction." },
    cerebellum: { dominance: 92, summary: "Silent gait, landing correction, whisker-linked movement precision." },
  },
};

const speciesRegions = (speciesId: SpeciesId): Region[] =>
  sharedRegions.map((region) => ({
    ...region,
    ...regionTuning[speciesId][region.id],
  }));

export const species: Species[] = [
  {
    id: "human",
    name: "Human",
    tagline: "Symbolic cognition and cultural memory",
    accent: "#32d7d2",
    secondaryAccent: "#a890ff",
    brainWeight: "1.35 kg",
    neuronCount: "86B",
    complexity: 99,
    intelligenceRank: "Abstract systems tier",
    sensoryStrengths: ["Language", "Tool planning", "Social inference"],
    lifespanRelation: "Long childhood supports extended cortical training.",
    memoryEstimate: "High episodic and semantic storage with symbolic compression.",
    adaptations: ["Theory of mind", "Speech sequencing", "Long-horizon planning"],
    brainBodyRatio: "1:40",
    specialization: "Executive integration and symbolic simulation",
    evolutionBadge: "Neocortex bloom",
    neuralDensity: 86,
    scale: 1,
    silhouette: "H",
    regions: speciesRegions("human"),
    missions: [
      {
        title: "Locate the hippocampal archive",
        description: "Use labels to isolate the memory circuit and trace recall pathways.",
        reward: "120 XP - Memory Cartographer",
        progress: 62,
      },
      {
        title: "Run executive control scan",
        description: "Compare frontal energy demand during planning and inhibition.",
        reward: "90 XP - Cortex Strategist",
        progress: 36,
      },
    ],
  },
  {
    id: "primate",
    name: "Primate",
    tagline: "Social strategy with agile visual cognition",
    accent: "#8a7cff",
    secondaryAccent: "#32d7d2",
    brainWeight: "95 g - 420 g",
    neuronCount: "6B - 28B",
    complexity: 84,
    intelligenceRank: "Adaptive social tier",
    sensoryStrengths: ["Depth vision", "Gesture reading", "Object permanence"],
    lifespanRelation: "Juvenile play tunes motor-social learning.",
    memoryEstimate: "Strong spatial, social, and reward memory.",
    adaptations: ["Canopy navigation", "Face recognition", "Tool discovery"],
    brainBodyRatio: "1:55",
    specialization: "Visual planning and group intelligence",
    evolutionBadge: "Social cortex",
    neuralDensity: 72,
    scale: 0.82,
    silhouette: "P",
    regions: speciesRegions("primate"),
    missions: [
      {
        title: "Compare hand-eye targeting",
        description: "Highlight visual and motor loops used for branch traversal.",
        reward: "80 XP - Arboreal Analyst",
        progress: 44,
      },
      {
        title: "Decode social memory",
        description: "Identify the regions that retain alliances and threat histories.",
        reward: "110 XP - Social Mapper",
        progress: 22,
      },
    ],
  },
  {
    id: "bird",
    name: "Bird",
    tagline: "Flight, song, and high-density navigation",
    accent: "#f5b95d",
    secondaryAccent: "#5ab7ff",
    brainWeight: "2 g - 20 g",
    neuronCount: "220M - 2B",
    complexity: 76,
    intelligenceRank: "Compact intelligence tier",
    sensoryStrengths: ["Flight vision", "Magnetic cues", "Song learning"],
    lifespanRelation: "Long-lived species show advanced memory and vocal learning.",
    memoryEstimate: "Dense navigation and vocal pattern libraries.",
    adaptations: ["Aerial prediction", "Song circuits", "Food caching"],
    brainBodyRatio: "1:65",
    specialization: "Efficient visual-motor processing",
    evolutionBadge: "Avian density",
    neuralDensity: 88,
    scale: 0.58,
    silhouette: "B",
    regions: speciesRegions("bird"),
    missions: [
      {
        title: "Trace flight stabilization",
        description: "Follow cerebellar pulses from wing motion to balance correction.",
        reward: "95 XP - Flight Systems",
        progress: 70,
      },
      {
        title: "Map song acquisition",
        description: "Activate temporal loops used for learned vocal sequences.",
        reward: "100 XP - Signal Composer",
        progress: 18,
      },
    ],
  },
  {
    id: "snake",
    name: "Snake",
    tagline: "Chemical tracking and reflexive predation",
    accent: "#79d38a",
    secondaryAccent: "#ff8fb5",
    brainWeight: "0.1 g - 3 g",
    neuronCount: "10M - 80M",
    complexity: 42,
    intelligenceRank: "Reflex-predator tier",
    sensoryStrengths: ["Chemical trails", "Heat sensing", "Strike timing"],
    lifespanRelation: "Energy-conserving cognition supports long dormancy cycles.",
    memoryEstimate: "Focused place, scent, and prey-association memory.",
    adaptations: ["Bifurcated scent maps", "Thermal targeting", "Strike reflexes"],
    brainBodyRatio: "1:1500",
    specialization: "Survival reflex and chemical navigation",
    evolutionBadge: "Reptilian core",
    neuralDensity: 31,
    scale: 0.45,
    silhouette: "S",
    regions: speciesRegions("snake"),
    missions: [
      {
        title: "Explore predator reflex systems",
        description: "Trigger a stimulus and watch brainstem-to-motor propagation.",
        reward: "75 XP - Reflex Specialist",
        progress: 52,
      },
      {
        title: "Reconstruct a scent trail",
        description: "Use olfactory dominance mode to follow chemical gradients.",
        reward: "85 XP - Chemosense Scout",
        progress: 12,
      },
    ],
  },
  {
    id: "fish",
    name: "Fish",
    tagline: "Aquatic orientation and rapid sensory loops",
    accent: "#5ab7ff",
    secondaryAccent: "#32d7d2",
    brainWeight: "0.02 g - 9 g",
    neuronCount: "1M - 250M",
    complexity: 38,
    intelligenceRank: "Aquatic reflex tier",
    sensoryStrengths: ["Lateral line", "Motion fields", "Schooling dynamics"],
    lifespanRelation: "Cognition varies widely with ecological niche.",
    memoryEstimate: "Route, predator, and feeding-location recall.",
    adaptations: ["Water vibration mapping", "School alignment", "Fast escape arcs"],
    brainBodyRatio: "1:1300",
    specialization: "Sensorimotor alignment in fluid environments",
    evolutionBadge: "Aquatic origin",
    neuralDensity: 35,
    scale: 0.38,
    silhouette: "F",
    regions: speciesRegions("fish"),
    missions: [
      {
        title: "Simulate schooling response",
        description: "Trigger a lateral-line input and trace coordinated movement.",
        reward: "70 XP - Current Reader",
        progress: 30,
      },
      {
        title: "Study primitive optic maps",
        description: "Compare aquatic visual processing with bird and cat systems.",
        reward: "80 XP - Evolution Scout",
        progress: 10,
      },
    ],
  },
  {
    id: "cat",
    name: "House Cat",
    tagline: "Nocturnal precision and predator learning",
    accent: "#ff8fb5",
    secondaryAccent: "#f5b95d",
    brainWeight: "25 g - 30 g",
    neuronCount: "250M",
    complexity: 64,
    intelligenceRank: "Predator specialist tier",
    sensoryStrengths: ["Night vision", "Whisker mapping", "Ambush timing"],
    lifespanRelation: "Exploration and play sharpen hunting circuits early.",
    memoryEstimate: "Strong spatial, routine, and associative memory.",
    adaptations: ["Low-light tracking", "Landing correction", "Territory mapping"],
    brainBodyRatio: "1:100",
    specialization: "Motion prediction and tactile navigation",
    evolutionBadge: "Predator optics",
    neuralDensity: 54,
    scale: 0.62,
    silhouette: "C",
    regions: speciesRegions("cat"),
    missions: [
      {
        title: "Compare cat vs human vision processing",
        description: "Overlay optic dominance and inspect low-light specialization.",
        reward: "100 XP - Vision Analyst",
        progress: 58,
      },
      {
        title: "Trace motor coordination pathways",
        description: "Follow cerebellar correction from leap to landing.",
        reward: "105 XP - Precision Pilot",
        progress: 40,
      },
    ],
  },
];

export const speciesById = new Map(species.map((entry) => [entry.id, entry]));

export const explorerModes: Array<{
  id: ExplorerMode;
  label: string;
  description: string;
}> = [
  {
    id: "explore",
    label: "Explore",
    description: "Inspect layered anatomical regions.",
  },
  {
    id: "compare",
    label: "Compare",
    description: "Overlay species-level differences.",
  },
  {
    id: "timeline",
    label: "Evolution Timeline",
    description: "Animate structures across evolutionary epochs.",
  },
  {
    id: "activity",
    label: "Neural Activity",
    description: "Simulate firing pathways and stimuli.",
  },
  {
    id: "quiz",
    label: "Quiz Mode",
    description: "Practice guided learning challenges.",
  },
  {
    id: "ar",
    label: "AR Mode",
    description: "Prepare immersive room-scale projection.",
  },
];

export const futureSpecies = [
  "Dolphins",
  "Dogs",
  "Elephants",
  "Octopus",
  "Whales",
  "Insects",
  "Dinosaurs",
  "AI neural networks",
];
